# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Serverless Framework Deploy AWS
        uses: hdev14/sls-deploy-action@1.0.0
        with:
          # AWS access key ID
          awsAccessKeyID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS secret access key
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # The specific stage name to deploy
          stage: 'production'
          # The specific region on AWS
          region: ${{ secrets.AWS_S3_REGION }}
    
